### PR TITLE
fix(filter): noop func always should returns state

### PR DESCRIPTION
**Pull request by tgfjt**
Hi 😭 
Unfortunately it's `undefined` whenever `setState` sets `state`.

### The cause:
`const filter = opts.filter || noop` & `if (filter) state = filter(state)`,
and `noop` returns `undefined`, then state is `undefined`.

### CODE REVIEW

**Comment by yoshuawuyts** [comment]
Nice thanks! On phone now but I'll merge once I get home

**Comment by tgfjt** [comment]
@yoshuawuyts 
Yeah, watch your step going home! 🐈

**Comment by yoshuawuyts** [comment]
sorry for the delay; `v2.0.1` :tada:

**Comment by tgfjt** [comment]
Thanks! 🍻

**Pull request merged**
